# 以下为自定义的全局变量，可以在 HTML 文件中引用，
# 比如代码：<h1>{{ site.title }}</h1> 
# 将会展示为设定的值，也可以自行添加其他自定义全局变量。
title:  曹恒的博客# 网站的标题

description: # 网站的描述，可能会出现在搜索引擎展示结果中
url: "https://caohengvs/caoheng.github.io" # 网站地址
github_repo: "caohengvs/caoheng.github.io"
github_profile: "https://github.com/caohengvs" # GitHub 个人主页
paginate: 5 # 主页展示的博客文章数量
user: "Noam" # Appears at sidebar
user_email: "caohengvs@163.com" # Appears at sidebar, remove whole variable if unwanted
contact_url: "https://caohengvs.github.io"

# jekyll 相关配置
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-sitemap
exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - COPYING
  - vendor
sass:
  style: compressed
future: true
permalink: /:year/:month/:day/:title
theme: jekyll-theme-slate
